title: Evan's Goofy Ahh Blog 2.1
description: "CSSE 1 & 2 student"
owner_name: Evan Svetina
github_username: EvanSvetina
github_repo: "blog2.1" 
baseurl: "/blog2.1"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
# remote_theme: pages-themes/midnight@v0.2.0
remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/snake.md
  - navigation/csse1-final.md
  - navigation/search.md
  - navigation/about.md
  - navigation/valfight.md
  - README4YML.md
